In [2]:
import numpy as np

In [19]:
data1 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)-1
pos1 = np.loadtxt("crosslinks-positionsTEST2.txt",skiprows=1)

In [4]:
posiciones = len(pos1)
particulas = len(data1)
print("posiciones",posiciones)
print("particulas",particulas)

posiciones 80657
particulas 80657


In [5]:
print(data1[22655:22660])

[[22655. 54938. 55170. 59871.]
 [22656. 11892. 18672. 47274.]
 [22658. 43112. 51762. 69408.]
 [22659.  1652.  7997. 65704.]
 [22660. 10438. 19546. 24998.]]


In [6]:
(22658-1)*8+1+1 #last +1 is because LastConfig2.bfm is 1-based

181258

In [29]:
del connections
import numpy as np
import numba
data1 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)-1
connections = data1.astype(int)
gap =np.where(np.diff(connections[:,0])!=1)[0]
guilty = connections[gap[0]+1, 0]  # the first overestimated ID
@numba.njit
def fix_connections(connections,guilty):
    for i in range(len(connections)):
        for j in range(0, connections.shape[1]):
            if connections[i,j] >= guilty:
                connections[i,j] -= 1
    return connections
connections = fix_connections(connections,guilty)

In [30]:
connections[22655:22660]

array([[22655, 54937, 55169, 59870],
       [22656, 11892, 18672, 47273],
       [22657, 43111, 51761, 69407],
       [22658,  1652,  7997, 65703],
       [22659, 10438, 19546, 24997]])

In [28]:
connections[-1]

array([80656, 36377, 44215, 51590])