In [1]:
import numpy as np

In [19]:
data1 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)-1
pos1 = np.loadtxt("crosslinks-positionsTEST2.txt",skiprows=1)

In [4]:
posiciones = len(pos1)
particulas = len(data1)
print("posiciones",posiciones)
print("particulas",particulas)

posiciones 80657
particulas 80657


In [5]:
print(data1[22655:22660])

[[22655. 54938. 55170. 59871.]
 [22656. 11892. 18672. 47274.]
 [22658. 43112. 51762. 69408.]
 [22659.  1652.  7997. 65704.]
 [22660. 10438. 19546. 24998.]]


In [6]:
(22658-1)*8+1+1 #last +1 is because LastConfig2.bfm is 1-based

181258

In [29]:
del connections
import numpy as np
import numba
data1 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)-1
connections = data1.astype(int)
gap =np.where(np.diff(connections[:,0])!=1)[0]
guilty = connections[gap[0]+1, 0]  # the first overestimated ID
@numba.njit
def fix_connections(connections,guilty):
    for i in range(len(connections)):
        for j in range(0, connections.shape[1]):
            if connections[i,j] >= guilty:
                connections[i,j] -= 1
    return connections
connections = fix_connections(connections,guilty)

In [30]:
connections[22655:22660]

array([[22655, 54937, 55169, 59870],
       [22656, 11892, 18672, 47273],
       [22657, 43111, 51761, 69407],
       [22658,  1652,  7997, 65703],
       [22659, 10438, 19546, 24997]])

In [28]:
connections[-1]

array([80656, 36377, 44215, 51590])

In [12]:
data1 = np.loadtxt("connected_xlinks2.txt",skiprows=1)-1
pos1 = np.loadtxt("crosslinks-positions2.txt",skiprows=1)

In [13]:
all_ids = set(range(len(pos1)))
connected_ids = set(data1[:,0])
missing_ids = all_ids - connected_ids
print("Missing IDs:", missing_ids)

Missing IDs: set()


In [14]:
ids_conn = data1[:,0].copy()
nxlink = len(pos1)
all_ids = np.arange(nxlink)

missing_from_conn = np.setdiff1d(all_ids, ids_conn)
extra_in_conn = np.setdiff1d(ids_conn, all_ids)

print("Missing from connections[:,0]:", missing_from_conn)
print("Extra/out-of-range in connections[:,0]:", extra_in_conn)
print("nxlink:", nxlink, "len(positions):", len(pos1))

Missing from connections[:,0]: []
Extra/out-of-range in connections[:,0]: [16129.]
nxlink: 16129 len(positions): 16129


In [15]:
# Find which row has 16129 in column 0
bad_rows = np.where(data1[:,0] == 16129)[0]  # after int cast: == 16129
print("Rows with out-of-range ID:", bad_rows)
print(data1[bad_rows])

Rows with out-of-range ID: [1771]
[[16129.  3392.  8888.  1020.  7575.]]
