In [2]:
import numpy as np

In [53]:
data1 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)-1
pos1 = np.loadtxt("crosslinks-positionsTEST2.txt",skiprows=1)

In [54]:
posiciones = len(pos1)
particulas = len(data1)
print("posiciones",posiciones)
print("particulas",particulas)

posiciones 80657
particulas 80657


In [62]:
print(data1[22655:22660])

[[22655. 54938. 55170. 59871.]
 [22656. 11892. 18672. 47274.]
 [22658. 43112. 51762. 69408.]
 [22659.  1652.  7997. 65704.]
 [22660. 10438. 19546. 24998.]]


In [ ]:
(22658-1)*8+1+1 #last +1 is because LastConfig2.bfm is 1-based

181257