In [1]:
import numpy as np

In [2]:
data1 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)-1
pos1 = np.loadtxt("crosslinks-positionsTEST2.txt",skiprows=1)

In [3]:
posiciones = len(pos1)
particulas = len(data1)
print("posiciones",posiciones)
print("particulas",particulas)

posiciones 80657
particulas 80657


In [9]:
datamichael = np.loadtxt("C:/Users/fernando/Nextcloud\PostDoc\IPF\simulation\michael\coord.dat")
particulasmichael = len(datamichael)
particulasmichael

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\fernando\AppData\Local\Temp\ipykernel_28120\925594445.py:1: SyntaxWarning: invalid escape sequence '\P'
  datamichael = np.loadtxt("C:/Users/fernando/Nextcloud\PostDoc\IPF\simulation\michael\coord.dat")


1048554

In [5]:
print(data1[22655:22660])

[[22655. 54938. 55170. 59871.]
 [22656. 11892. 18672. 47274.]
 [22658. 43112. 51762. 69408.]
 [22659.  1652.  7997. 65704.]
 [22660. 10438. 19546. 24998.]]


In [6]:
(22658-1)*8+1+1 #last +1 is because LastConfig2.bfm is 1-based

181258

In [29]:
del connections
import numpy as np
import numba
data1 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)-1
connections = data1.astype(int)
gap =np.where(np.diff(connections[:,0])!=1)[0]
guilty = connections[gap[0]+1, 0]  # the first overestimated ID
@numba.njit
def fix_connections(connections,guilty):
    for i in range(len(connections)):
        for j in range(0, connections.shape[1]):
            if connections[i,j] >= guilty:
                connections[i,j] -= 1
    return connections
connections = fix_connections(connections,guilty)

In [30]:
connections[22655:22660]

array([[22655, 54937, 55169, 59870],
       [22656, 11892, 18672, 47273],
       [22657, 43111, 51761, 69407],
       [22658,  1652,  7997, 65703],
       [22659, 10438, 19546, 24997]])

In [28]:
connections[-1]

array([80656, 36377, 44215, 51590])

In [12]:
data1 = np.loadtxt("connected_xlinks2.txt",skiprows=1)-1
pos1 = np.loadtxt("crosslinks-positions2.txt",skiprows=1)

In [13]:
all_ids = set(range(len(pos1)))
connected_ids = set(data1[:,0])
missing_ids = all_ids - connected_ids
print("Missing IDs:", missing_ids)

Missing IDs: set()


In [14]:
ids_conn = data1[:,0].copy()
nxlink = len(pos1)
all_ids = np.arange(nxlink)

missing_from_conn = np.setdiff1d(all_ids, ids_conn)
extra_in_conn = np.setdiff1d(ids_conn, all_ids)

print("Missing from connections[:,0]:", missing_from_conn)
print("Extra/out-of-range in connections[:,0]:", extra_in_conn)
print("nxlink:", nxlink, "len(positions):", len(pos1))

Missing from connections[:,0]: []
Extra/out-of-range in connections[:,0]: [16129.]
nxlink: 16129 len(positions): 16129


In [15]:
# Find which row has 16129 in column 0
bad_rows = np.where(data1[:,0] == 16129)[0]  # after int cast: == 16129
print("Rows with out-of-range ID:", bad_rows)
print(data1[bad_rows])

Rows with out-of-range ID: [1771]
[[16129.  3392.  8888.  1020.  7575.]]


In [1]:
import numpy as np

In [2]:
pos1 = np.loadtxt("crosslinks-positionsTEST1.txt",skiprows=1)
pos2 = np.loadtxt("crosslinks-positionsTEST2.txt",skiprows=1)

In [3]:
len(pos1), len(pos2)

(80657, 80657)

In [4]:
for i in range(len(pos1)):
    if not np.allclose(pos1[i], pos2[i]):
        print(f"Difference at index {i}: pos1={pos1[i]}, pos2={pos2[i]}")

In [14]:
conn1 = np.loadtxt("connected_xlinksTEST1.txt",skiprows=1)
conn2 = np.loadtxt("connected_xlinksTEST2.txt",skiprows=1)

In [15]:
len(conn1), len(conn2)

(80657, 80657)

In [16]:
conn1 = conn1[np.argsort(conn1[:, 0], kind="stable")]
conn1

array([[1.0000e+00, 1.7312e+04, 3.5040e+04, 2.0793e+04],
       [2.0000e+00, 4.7776e+04, 8.6060e+03, 0.0000e+00],
       [3.0000e+00, 1.4627e+04, 1.7129e+04, 1.5835e+04],
       ...,
       [8.0656e+04, 6.7614e+04, 8.2050e+03, 2.5022e+04],
       [8.0657e+04, 8.4300e+03, 2.5943e+04, 4.7636e+04],
       [8.0658e+04, 3.6379e+04, 4.4217e+04, 5.1592e+04]], shape=(80657, 4))

In [17]:
for i in range(len(conn1)):
    if not np.allclose(conn1[i], conn2[i]):
        print(f"Difference at index {i}: conn1={conn1[i]}, conn2={conn2[i]}")

Difference at index 0: conn1=[1.0000e+00 1.7312e+04 3.5040e+04 2.0793e+04], conn2=[1.0000e+00 1.7312e+04 2.0793e+04 3.5040e+04]
Difference at index 1: conn1=[2.0000e+00 4.7776e+04 8.6060e+03 0.0000e+00], conn2=[2.0000e+00 8.6060e+03 4.7776e+04 0.0000e+00]
Difference at index 2: conn1=[3.0000e+00 1.4627e+04 1.7129e+04 1.5835e+04], conn2=[3.0000e+00 1.4627e+04 1.5835e+04 1.7129e+04]
Difference at index 3: conn1=[4.0000e+00 7.7199e+04 4.0820e+03 5.6401e+04], conn2=[4.0000e+00 4.0820e+03 5.6401e+04 7.7199e+04]
Difference at index 4: conn1=[5.0000e+00 3.3901e+04 5.0000e+00 5.0000e+00], conn2=[5.0000e+00 5.0000e+00 3.3901e+04 0.0000e+00]
Difference at index 5: conn1=[6.0000e+00 6.6032e+04 8.9470e+03 5.4118e+04], conn2=[6.0000e+00 8.9470e+03 5.4118e+04 6.6032e+04]
Difference at index 7: conn1=[8.0000e+00 5.6790e+04 5.9082e+04 2.2972e+04], conn2=[8.0000e+00 2.2972e+04 5.6790e+04 5.9082e+04]
Difference at index 8: conn1=[9.0000e+00 4.7805e+04 4.5876e+04 0.0000e+00], conn2=[9.0000e+00 4.5876e+04

In [9]:
conn2

array([[1.0000e+00, 1.7312e+04, 2.0793e+04, 3.5040e+04],
       [2.0000e+00, 8.6060e+03, 4.7776e+04, 0.0000e+00],
       [3.0000e+00, 1.4627e+04, 1.5835e+04, 1.7129e+04],
       ...,
       [8.0656e+04, 8.2050e+03, 2.5022e+04, 6.7614e+04],
       [8.0657e+04, 8.4300e+03, 2.5943e+04, 4.7636e+04],
       [8.0658e+04, 3.6379e+04, 4.4217e+04, 5.1592e+04]], shape=(80657, 4))